//FUNCTION WHICH PRODUCES THE MULTITAP ENCODING OF A SINGLE
//INPUT CHARACTER "ch", AND STORES IT IN THE STRING PARAMETER
//"multitap". RETURNS THE LENGTH OF THE MULTITAP ENCODING.
int encode_character(const char ch, char* multitap);

//FUNCTION WHICH PRODUCES THE MULTITAP ENCODING OF A PLAINTEXT
//INPUT STRING "plaintext" AND STORES IT IN THE STRING PARAMETER
//"multitap".
void encode(const char* plaintext, char* multitap);
